config/routes.rb
Rails.application.routes.draw do
  resources :perfils
  resources :usuarios
  resources :items
  root 'usuarios#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
validates :i1, presence: true
	validate :llenado_correcto
	validate :puntaje_valido

def llenado_correcto
	if i1.to_i > 0 
		if i2 == nil
			errors.add(:i2, "Por favor, contesta la segunda pregunta")
		end
		if i3 == nil
			errors.add(:i3, "Por favor, contesta la tecera pregunta")
		end
	end

	if i1.to_i == 0
		if i2.to_i > 0 || i3.to_i > 0
			errors.add(:i1, "Si no ha consumido alcohol en el último año, por favor revisa las preguntas dos y tres")
		end
	end
end

def puntaje_valido
	if i1.to_i == 0 || i1.to_i == 1 || i1.to_i == 2 || i1.to_i == 3 || i1.to_i == 4 
	else errors.add(:i1, "El puntaje de la pregunta uno no es válido")
	end

	if i2.to_i == 0 || i2.to_i == 1 || i2.to_i == 2 || i2.to_i == 3 || i2.to_i == 4 
	else errors.add(:i1, "El puntaje de la pregunta uno no es válido")
	end

	if i3.to_i == 0 || i3.to_i == 1 || i3.to_i == 2 || i3.to_i == 3 || i3.to_i == 4 
	else errors.add(:i1, "El puntaje de la pregunta uno no es válido")
	end
end


end

app/models/perfil.rb
class Perfil < ApplicationRecord
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.total = @item.i1.to_i + @item.i2.to_i + @item.i3.to_i
    # raise params[:item].inspect

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:i1, :i2, :i3, :total)
    end
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil was successfully created.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfils_url, notice: 'Perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:sexo, :f_nac, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> no se puede finalizar el cuestionario:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<form>
  
<div class="form-group">
    <label for="Select1"><h2>¿Con qué frecuencia consume alguna bebida alcoholica?</h2></label>
    <select  class="form-control" id="Select1" name= "item[i1]">
      <option value="0">Nunca</option>
      <option value="1">1 o menos veces al mes</option>
      <option value="2">De 2 a 4 veces al mes</option>
      <option value="3">De 2 a 3 veces a la semana</option>
      <option value="4">4 o más veces a la semana</option>
    </select>
</div>

<div class="form-group">
    <label for="Select2">¿Cuantos TRAGOS de alcohol suele tomar en un día de consumo normal?</label>
    <select  class="form-control" id="Select2" name= "item[i2]">
      <option value="0">1 ó 2</option>
      <option value="1">3 ó 4</option>
      <option value="2">5 ó 6</option>
      <option value="3">7, 8 ó 9</option>
      <option value="4">10 o más</option>
    </select>
  </div>

<div class=" container row" id="tragos">
 <span class="col-md-3 col-sm-3 col-lg-3"><img src=<%= image_url "lata_cerveza.jpg" %> class="mg-responsive" alt="Responsive image" ></span>

 <span class="col-md-3 col-sm-3 col-lg-3"><img src=<%= image_url "copa_vino.jpg" %> class="img-responsive" alt="Responsive image" ></span>

<span class="col-md-3 col-sm-3 col-lg-3">
<img src=<%= image_url "corto_licor.jpg" %> class="img-responsive" alt="Responsive image" ></span>
</div>


<div class="form-group">
    <label for="Select3">¿Con qué frecuencia toma 5 o más TRAGOS  en un sólo día?</label>
    <select  class="form-control" id="Select3" name= "item[i3]">
      <option value="0">Nunca</option>
      <option value="1">Menos de una vez al mes</option>
      <option value="2">Mensualmente</option>
      <option value="3">Semanalmente</option>
      <option value="4">A diario o casi a diario</option>
    </select>
  </div>

  <div class="actions" style="clear: both"> 
  <br>
    <%= form.submit("Listo") %>
  </div>

<% end %>
</form>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Audits realizados</h1>

<table>
  <thead>
    <tr>
      <th>Preg 1  </th>
      <th>Preg 2  </th>
      <th>Preg 3  </th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.i1 %></td>
        <td><%= item.i2 %></td>
        <td><%= item.i3 %></td>
        <td><%= item.total %></td>
       <!--  <td><%= link_to 'Mostrar', item %></td>
        <td><%= link_to 'Editar', edit_item_path(item) %></td> -->
        <td><%= link_to 'Borrar', item, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Hacer Audit', new_item_path %>

app/views/items/new.html.erb
<div class="container" ></div>
 <div class="row">
  <div class="col-lg-2 col-md-2" ></div>
  <div class="col-lg-8 col-md-8">
	<div class="jumbotron">
 	 <h1>Cuestionario Breve</h1>
 	 <p class="lead"><h3>Contesta estas preguntas sobre tu consumo de bebidas alcoholicas <b> durante el último año</b></h3></p>

		<%= render 'form', item: @item %>

		<%= link_to 'Volver', items_path %>

	</div>
   </div> <!-- Cierra col -->
 </div> <!-- cierra row -->
</div>
<div> <!-- cierra conrainer -->

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>I1:</strong>
  <%= @item.i1 %>
</p>

<p>
  <strong>I2:</strong>
  <%= @item.i2 %>
</p>

<p>
  <strong>I3:</strong>
  <%= @item.i3 %>
</p>

<p>
  <strong>Total:</strong>
  <%= @item.total %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="#">
      <img src=<%= image_url "footer-mutualseguridad.png" %>  class="d-inline-block align-top" alt=""></img>
       Intervenciones Breves
    </a>
<p class="navbar-text" >
    Usuario
  </p>

</nav>



    <%= yield %>

</body>

<footer class="panel-footer">
    <div class="container">
      <div class="row">
        <section id="hours" class="col-sm-4">
          <span>Versión:</span><br>
          1.0 <br>
          En construcción<br>
          <hr class="visible-xs">
        </section>
        <section id="address" class="col-sm-4">
          <span>Proyecto:</span><br>
          Intervención Breve vía Internet<br>
          Basado en AUDIT y AUDIT-BI
          <hr class="visible-xs">
        </section>
        <section id="testimonials" class="col-sm-4">
          <p>"Esta app ha sido desarrollada para detectar el uso excesivo de alcohol y proveer ayuda oportuna"</p>
          
        </section>
      </div>
      <div class="text-center">&copy; Proyecto SUCESO Poblete - Barticevic</div>
      <br>
    </div>
  </footer>

 
</html>

app/views/perfils/_form.html.erb
<%= form_with(model: perfil, local: true) do |form| %>
  <% if perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :perfil_sexo %>
  </div>

  <div class="field">
    <%= form.label :f_nac %>
    <%= form.date_select :f_nac, id: :perfil_f_nac %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id, id: :perfil_usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perfils/edit.html.erb
<h1>Editing Perfil</h1>

<%= render 'form', perfil: @perfil %>

<%= link_to 'Show', @perfil %> |
<%= link_to 'Back', perfils_path %>

app/views/perfils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perfils</h1>

<table>
  <thead>
    <tr>
      <th>Sexo</th>
      <th>F nac</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perfils.each do |perfil| %>
      <tr>
        <td><%= perfil.sexo %></td>
        <td><%= perfil.f_nac %></td>
        <td><%= perfil.usuario %></td>
        <td><%= link_to 'Show', perfil %></td>
        <td><%= link_to 'Edit', edit_perfil_path(perfil) %></td>
        <td><%= link_to 'Destroy', perfil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perfil', new_perfil_path %>

app/views/perfils/new.html.erb
<h1>New Perfil</h1>

<%= render 'form', perfil: @perfil %>

<%= link_to 'Back', perfils_path %>

app/views/perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sexo:</strong>
  <%= @perfil.sexo %>
</p>

<p>
  <strong>F nac:</strong>
  <%= @perfil.f_nac %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @perfil.usuario %>
</p>

<%= link_to 'Edit', edit_perfil_path(@perfil) %> |
<%= link_to 'Back', perfils_path %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<form class="form-horizontal">
  <div class="form-group">
    <label for="usuario_nombre" class="col-sm-2 control-label">Usuario</label>
    <div class="col-sm-10">
      <%= form.text_field :nombre, id: :usuario_nombre, class: "form-control", placeholder: "Nombre"%>
    </div>
  </div>
  <div class="form-group">
    <label for="password_digest_usuario_password_digest" class="col-sm-2 control-label">Contraseña</label>
    <div class="col-sm-10">
      <%= password_field :password_digest, :usuario_password_digest, class: "form-control" , placeholder: "contraseña"%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="actions">
        <button type="submit" class="btn btn-default">
          <%= form.submit %>
        </button>
      </div>
    </div>
  </div>
</form>

 <!-- <button type="submit" class="btn btn-default">Sign in</button> -->

 
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.password_digest %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<div class="container" ></div>
 <div class="row">
  <div class="col-lg-3 col-md-2" ></div>
  <div class="col-lg-6 col-md-8">	
	<div class="jumbotron">
		<h1 class="text-center">Bienvenido</h1>

		<%= render 'form', usuario: @usuario %>

		<%= link_to 'Back', usuarios_path %>
	</div>
  </div> <!-- Cierra col -->
 </div> <!-- cierra row -->
 </div>
<div> <!-- cierra conrainer -->

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @usuario.password_digest %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>